name: Continuous Delivery
on:
  pull_request:
    branches:
      - main
jobs:
  deliver:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Simulation CD
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            '**.py'
            README.md
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/checkout@v4
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R